# Generated by Django 2.1.4 on 2018-12-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
